const list = document.createElement("ul");
const apple = document.createElement("li");
apple.innerText = "Apple";
list.append(apple);
const orange = document.createElement("li");
orange.innerText = "Orange";
list.append(orange);
const grape = document.createElement("li");
grape.innerText = "Grape";
list.append(grape);